name:               "Lastab"
description:        "Somebody"

meta_keywords:      "lastab batsal-awaley ruby-developer elixir-drinker archlinux-fan"
meta_description:   "Elixir Drinker/Ruby Lover/Archlinux fan. Geek by nature, Elixir drunkard by choice!"

url:                ""
author:             "lastab"
email:              "lastab.me@gmail.com"
# gravatar_hash:      ""
twitter:            "_lastab"
github:             "lastab"
# pinterest:          ""
linkedin:           "batsal"
# facebook:           ""
gitlab:             "lastab"

disqus_shortname:   ""

background:         "/img/background.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
# permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
